#!/usr/bin/env python
#
# This code was taken from the following url and ackownledged with thanks
# https://gist.github.com/alimuldal/eb0f4eea8af331b2a890
import numpy
import sys
import timeit

print("version: %s" % numpy.__version__)
print("maxint:  %i\n" % sys.maxsize)

numpy.show_config()

setup = "import numpy; x = numpy.random.random((20000, 2000))"
count = 5

t = timeit.Timer("numpy.dot(x, x.T)", setup=setup)
print("\ndot: %f sec" % (t.timeit(count) / count))
