---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Figure01_Polarisation_Picture/Figure01_Polarisation_Picture.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/223746/articles/279061/master/file/figures/Figure01_Polarisation_Picture/Figure01_Polarisation_Picture.png"
    folder_url: "/users/223746/articles/279061/master/folder/figures/Figure01_Polarisation_Picture"
